# Generated by Django 5.0.6 on 2026-04-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('bat-dong-san', 'Tin tức'), ('do-dien-tu', 'Airdrop'), ('xe-co', 'Testnet')], default='bat-dong-san', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
